Repository jupyterlab/debugger, pull requests merged in 2019-12, with the labels that each got.

#240 Allow setting breakpoints in out-of-focus cells
  package.json
  src/handlers/editor.ts
  src/handlers/notebook.ts
  style/breakpoints.css
Labels: enhancement, ui

#241 Clickable breakpoints
  src/breakpoints/body.tsx
  src/breakpoints/index.ts
  src/editors/index.ts
  src/handlers/editor.ts
  src/handlers/tracker.ts
  style/breakpoints.css
Labels: ui

#242 Single mode debugger
  src/debugger.ts
  src/editors/index.ts
  src/handlers/console.ts
  src/handlers/editor.ts
  src/handlers/file.ts
  src/handlers/notebook.ts
  src/handlers/tracker.ts
  src/index.ts
  src/service.ts
  src/sources/index.ts
  src/tokens.ts
  style/breakpoints.css
  style/editors.css
  style/index.css
  style/sources.css
  tests/src/debugger.spec.ts
Labels: ui

#247 Open the source of a breakpoint on click
  src/callstack/body.tsx
  src/callstack/index.ts
  src/handlers/tracker.ts
  src/index.ts
  src/sources/index.ts
Labels: enhancement, ui

#248 Add support for breakpoints in modules and files
  src/handlers/editor.ts
  src/handlers/tracker.ts
  src/service.ts
  src/sources/index.ts
  src/tokens.ts
Labels: enhancement, ui

#256 Remove internal mount command
  src/index.ts
Labels: ui

#258 Replace "Environment" by the jp-BugIcon
  src/debugger.ts
Labels: ui

#257 Add drop shadows to headers
  style/sidebar.css
Labels: ui

#262 Align breakpoint line numbers
  src/breakpoints/body.tsx
  style/breakpoints.css
Labels: ui

#260 Show source path above the read-only preview editor
  src/breakpoints/index.ts
  src/callstack/index.ts
  src/sources/index.ts
  src/variables/index.ts
  style/sidebar.css
  style/sources.css
Labels: enhancement, ui

#279 Fix enabled commands on debugger closed
  src/debugger.ts
  src/index.ts
  src/service.ts
Labels: ui

#239 Add life-cycle button in toolbar of notebook and console panel.
  src/index.ts
  src/service.ts
  src/session.ts
  src/tokens.ts
  style/console.css
  style/icons.css
  style/index.css
Labels: ui

#282 Add tests for service.hasStoppedThreads()
  tests/src/service.spec.ts
Labels: testing

#298 Remove close command
  src/index.ts
Labels: ui

#301 Remove create command
  src/index.ts
Labels: ui

#308 Clear the sidebar UI
  src/debugger.ts
  src/handlers/tracker.ts
  src/index.ts
  src/service.ts
Labels: ui

#313 Add screencast to the README
  README.md
  screencast.gif
Labels: documentation

#327 Make breakpoints and callstack scrollable
  style/breakpoints.css
  style/callstack.css
  style/sidebar.css
Labels: breakpoints, callstack, ui
